/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCompanyRouteImport } from './routes/_authenticated/admin.company'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminInquiriesIndexRouteImport } from './routes/_authenticated/admin.inquiries.index'
import { Route as AuthenticatedAdminInquiriesIdRouteImport } from './routes/_authenticated/admin.inquiries.$id'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin.products.$id'
import { Route as AuthenticatedAdminRfqsIndexRouteImport } from './routes/_authenticated/admin.rfqs.index'
import { Route as AuthenticatedAdminRfqsIdRouteImport } from './routes/_authenticated/admin.rfqs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCompanyRoute =
  AuthenticatedAdminCompanyRouteImport.update({
    id: '/admin/company',
    path: '/admin/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/admin/content',
    path: '/admin/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminInquiriesIndexRoute =
  AuthenticatedAdminInquiriesIndexRouteImport.update({
    id: '/admin/inquiries/',
    path: '/admin/inquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInquiriesIdRoute =
  AuthenticatedAdminInquiriesIdRouteImport.update({
    id: '/admin/inquiries/$id',
    path: '/admin/inquiries/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/admin/products/$id',
    path: '/admin/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRfqsIndexRoute =
  AuthenticatedAdminRfqsIndexRouteImport.update({
    id: '/admin/rfqs/',
    path: '/admin/rfqs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRfqsIdRoute =
  AuthenticatedAdminRfqsIdRouteImport.update({
    id: '/admin/rfqs/$id',
    path: '/admin/rfqs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/capabilities': typeof CapabilitiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRouteWithChildren
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/inquiries/$id': typeof AuthenticatedAdminInquiriesIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/rfqs/$id': typeof AuthenticatedAdminRfqsIdRoute
  '/admin/inquiries/': typeof AuthenticatedAdminInquiriesIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/rfqs/': typeof AuthenticatedAdminRfqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/capabilities': typeof CapabilitiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRouteWithChildren
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/inquiries/$id': typeof AuthenticatedAdminInquiriesIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/rfqs/$id': typeof AuthenticatedAdminRfqsIdRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/rfqs': typeof AuthenticatedAdminRfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/capabilities': typeof CapabilitiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRouteWithChildren
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/_authenticated/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/inquiries/$id': typeof AuthenticatedAdminInquiriesIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/rfqs/$id': typeof AuthenticatedAdminRfqsIdRoute
  '/_authenticated/admin/inquiries/': typeof AuthenticatedAdminInquiriesIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/rfqs/': typeof AuthenticatedAdminRfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/capabilities'
    | '/contact'
    | '/industries'
    | '/products'
    | '/quality'
    | '/quote'
    | '/reset-password'
    | '/products/$slug'
    | '/admin/company'
    | '/admin/content'
    | '/admin/media'
    | '/admin/'
    | '/admin/inquiries/$id'
    | '/admin/products/$id'
    | '/admin/rfqs/$id'
    | '/admin/inquiries/'
    | '/admin/products/'
    | '/admin/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/capabilities'
    | '/contact'
    | '/industries'
    | '/products'
    | '/quality'
    | '/quote'
    | '/reset-password'
    | '/products/$slug'
    | '/admin/company'
    | '/admin/content'
    | '/admin/media'
    | '/admin'
    | '/admin/inquiries/$id'
    | '/admin/products/$id'
    | '/admin/rfqs/$id'
    | '/admin/inquiries'
    | '/admin/products'
    | '/admin/rfqs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/capabilities'
    | '/contact'
    | '/industries'
    | '/products'
    | '/quality'
    | '/quote'
    | '/reset-password'
    | '/products/$slug'
    | '/_authenticated/admin/company'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/inquiries/$id'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/rfqs/$id'
    | '/_authenticated/admin/inquiries/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QualityRoute: typeof QualityRoute
  QuoteRoute: typeof QuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/company': {
      id: '/_authenticated/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AuthenticatedAdminCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inquiries/': {
      id: '/_authenticated/admin/inquiries/'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inquiries/$id': {
      id: '/_authenticated/admin/inquiries/$id'
      path: '/admin/inquiries/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rfqs/': {
      id: '/_authenticated/admin/rfqs/'
      path: '/admin/rfqs'
      fullPath: '/admin/rfqs/'
      preLoaderRoute: typeof AuthenticatedAdminRfqsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rfqs/$id': {
      id: '/_authenticated/admin/rfqs/$id'
      path: '/admin/rfqs/$id'
      fullPath: '/admin/rfqs/$id'
      preLoaderRoute: typeof AuthenticatedAdminRfqsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCompanyRoute: typeof AuthenticatedAdminCompanyRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminInquiriesIdRoute: typeof AuthenticatedAdminInquiriesIdRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminRfqsIdRoute: typeof AuthenticatedAdminRfqsIdRoute
  AuthenticatedAdminInquiriesIndexRoute: typeof AuthenticatedAdminInquiriesIndexRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminRfqsIndexRoute: typeof AuthenticatedAdminRfqsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCompanyRoute: AuthenticatedAdminCompanyRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminInquiriesIdRoute: AuthenticatedAdminInquiriesIdRoute,
  AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
  AuthenticatedAdminRfqsIdRoute: AuthenticatedAdminRfqsIdRoute,
  AuthenticatedAdminInquiriesIndexRoute: AuthenticatedAdminInquiriesIndexRoute,
  AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  AuthenticatedAdminRfqsIndexRoute: AuthenticatedAdminRfqsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QualityRoute: QualityRoute,
  QuoteRoute: QuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
